name: CI Pipeline

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  

jobs:
  backend:
    runs-on: ubuntu-latest 

    steps:
      - name: Check out repository
        uses: actions/checkout@v2  

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  

      - name: Install backend dependencies
        run: |
          cd server  # Vai para o diretório do backend
          npm install  # Instala as dependências do backend

      - name: Run backend tests
        run: |
          cd server  # Vai para o diretório do backend
          npm test  # Executa os testes do backend (Jest)
  frontend:
    runs-on: ubuntu-latest  

    steps:
      - name: Check out repository
        uses: actions/checkout@v2 

      - name: Set up Node.js for React
        uses: actions/setup-node@v2
        with:
          node-version: '14' 

      - name: Install frontend dependencies
        run: |
          cd client  # Vai para o diretório do frontend
          npm install  # Instala as dependências do frontend

      - name: Run frontend tests
        run: |
          cd client  # Vai para o diretório do frontend
          npm test  # Executa os testes do frontend
